esphome:
  platformio_options:
    board_build.flash_mode: dio
    board_upload.maximum_size: 16777216
      
esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 16MB
  framework:
    type: esp-idf
    version: 5.1.6
    platform_version: 51.3.7

    sdkconfig_options:
      CONFIG_ESP32_S3_BOX_BOARD: "y"
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"

      #make sure to disable it also in psram component
      CONFIG_SPIRAM_IGNORE_NOTFOUND: "n"
      #CONFIG_SPIRAM_RODATA: "y"
      #CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"
      CONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY: "y"

      # FreeRTOS
      CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY: "y"
      
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y" 

      # LWIP
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: "y"
      CONFIG_LWIP_TCP_MSS: "1200"
      CONFIG_LWIP_TCP_WND_DEFAULT: "19200"
      CONFIG_LWIP_WND_SCALE: "y"
      CONFIG_LWIP_TCP_RCV_SCALE: "1"
      CONFIG_LWIP_TCPIP_RECVMBOX_SIZE: "64"
      CONFIG_LWIP_TCP_RECVMBOX_SIZE: "32"
      CONFIG_LWIP_TCP_SACK_OUT: "y"
      CONFIG_LWIP_TCP_TIMESTAMPS: "y"
      
      #CONFIG_LWIP_MAX_SOCKETS:  "16"  
      #CONFIG_VFS_MAX_OPEN_FILES: "32" 
      
      # Queue incoming out-of-order segments
      CONFIG_LWIP_TCP_QUEUE_OOSEQ: "y"
      # 0 <= TCP_OOSEQ_MAX_PBUFS <= CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM/(MAX_TCP_NUMBER + 1) 
      # default 4 if !(SPIRAM_TRY_ALLOCATE_WIFI_LWIP && !SPIRAM_IGNORE_NOTFOUND)
      # default 0 if  (SPIRAM_TRY_ALLOCATE_WIFI_LWIP && !SPIRAM_IGNORE_NOTFOUND)
      # 0: unlimited, range: 0-12
      CONFIG_LWIP_TCP_OOSEQ_MAX_PBUFS: "4"
      
      
      CONFIG_TCP_OVERSIZE_MSS: "y"
      
      
      # WiFi
      CONFIG_ESP_WIFI_AMPDU_RX_ENABLED: "y"
      CONFIG_ESP_WIFI_RX_BA_WIN: "20"
      CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM: "10"
      CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM: "128"
      
      ESP_WIFI_AMSDU_TX_ENABLED: "n" # default n, depends on (ESP_WIFI_CACHE_TX_BUFFER_NUM >= 2)
      CONFIG_ESP_WIFI_AMPDU_TX_ENABLED: "y"
      CONFIG_ESP_WIFI_TX_BA_WIN: "10"
      
      CONFIG_ESP_WIFI_STATIC_TX_BUFFER_NUM: "8"
      CONFIG_ESP_WIFI_CACHE_TX_BUFFER_NUM: "32" #default 32, depends on (SPIRAM_TRY_ALLOCATE_WIFI_LWIP && !SPIRAM_IGNORE_NOTFOUND)

      # depends on !(SPIRAM_TRY_ALLOCATE_WIFI_LWIP && !SPIRAM_IGNORE_NOTFOUND)
      # CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER: "y"
      # CONFIG_ESP32_WIFI_TX_BUFFER_TYPE: "1"
      # CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER_NUM: "32"

      # BT
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"

      # MDNS
      CONFIG_MDNS_MEMORY_ALLOC_SPIRAM: "y"

psram:
  mode: octal
  speed: 80MHz

i2c:
  - id: i2c_0
    sda: GPIO5
    scl: GPIO6
    frequency: 400kHz
    scan: True

spi:
  - id: spi_0
    clk_pin:  GPIO12
    mosi_pin: GPIO11
    miso_pin: GPIO13
    interface: SPI2

i2s_audio:
  - id: i2s_shared
    i2s_lrclk_pin: GPIO07
    i2s_bclk_pin: GPIO08
    i2s_mclk_pin: GPIO16
    access_mode: duplex
    i2s_mode: secondary
    use_legacy: false
