external_components:  
  - source:
      type: git
      url: https://github.com/FutureProofHomes/Satellite1-ESPHome
      ref: develop
    refresh: 1s
    components: [ version ]

debug:
  update_interval: 5s

# # OPTIONAL Persist logs to a an MQTT broker so you can go back in time and inspect them.  Read more here: https://esphome.io/components/mqtt.html
# mqtt:
#   broker: homeassistant.local
#   port: 1883
#   username: <mqtt_username_here>
#   password: <mqtt_password_here>
#   # topic_prefix: <set_this_if_you_are_logging_multiple_satellite1_devices>

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
      entity_category: "diagnostic"
    reset_reason:
      name: "Reset Reason"
      entity_category: "diagnostic"

  - platform: version
    name: "Firmware Version"
    hide_timestamp: true


sensor:
  - platform: debug
    free:
      name: "Heap Free"
      entity_category: "diagnostic"
    block:
      name: "Heap Max Block"
      entity_category: "diagnostic"
    loop_time:
      name: "Loop Time"
      entity_category: "diagnostic"
    psram:
      name: "Free PSRAM"
      entity_category: "diagnostic"
  - platform: wifi_signal
    name: "Wi-Fi Signal Strength"
    entity_category: "diagnostic"
    update_interval: 60s

  - platform: internal_temperature
    name: "Internal ESP Temperature"
    entity_category: "diagnostic"
    update_interval: 60s

button:
  # Restarts Sat1 to safe mode
  - platform: safe_mode
    name: "Restart Sat1 (Safe Mode)"
    entity_category: diagnostic
  
  - platform: template
    id: xmos_hardware_reset
    name: "XMOS Hardware Reset"
    entity_category: diagnostic
    on_press:
      then:
        - satellite1.xmos_hardware_reset

  # Flashes Sat1 HAT with specific XMOS firmware
  - platform: template
    id: flash_satellite
    name: "XMOS Flash ${xmos_fw_version}"
    entity_category: diagnostic
    on_press:
      then:
        - memory_flasher.write_image:
            image_version: ${xmos_fw_version}
            image_file: https://raw.githubusercontent.com/FutureProofHomes/Documentation/refs/heads/main/assets/firmware/xmos/${xmos_fw_version}/satellite1_firmware_fixed_delay.factory.bin
            md5_url: https://raw.githubusercontent.com/FutureProofHomes/Documentation/refs/heads/main/assets/firmware/xmos/${xmos_fw_version}/satellite1_firmware_fixed_delay.factory.md5

  # Flashes Sat1 HAT with XMOS firmware embedded in the ESP32
  - platform: template
    id: flash_embedded
    name: "XMOS Flash Embedded FW"
    entity_category: diagnostic
    on_press:
      then:
        - memory_flasher.write_embedded_image:

  # Wipes the Satellite1 HAT XMOS Chip
  - platform: template
    id: erase_xmos_flash
    name: "XMOS Erase Chip"
    entity_category: diagnostic
    on_press:
      then:
        - memory_flasher.erase:
