# This is a developer configuration that enables the UDP stream component and adds switches to toggle between the ASR and Comm microphones.
# You can read more about how to use this configuration here: https://github.com/FutureProofHomes/Satellite1-ESPHome/tree/develop/tests/mic_streaming

external_components:  
  - source:
      type: git
      url: https://github.com/FutureProofHomes/Satellite1-ESPHome
      ref: develop
    components: [ udp_stream ]


# Separate UDP Stream configurations for each microphone
udp_stream:
  id: udp_streamer
  microphone: asr_mic  # Default microphone to prevent validation errors


# Switches to toggle between ASR and Comm microphones
switch:
  - platform: template
    name: "UDP Stream ASR Mic"
    entity_category: "diagnostic"
    id: use_asr_mic
    icon: mdi:microphone
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    on_turn_on:
      - logger.log: "Switching to ASR Mic for UDP stream"
      - lambda: |-
          if (id(udp_streamer).is_running()) {
            id(udp_streamer).request_stop();  // Stop current stream
            delay(500);  // Wait for stream to stop
          }
          id(udp_streamer).set_microphone(id(asr_mic));  // Set ASR mic
          id(udp_streamer).request_start(true);  // Start stream with ASR mic
      - switch.turn_off: use_comm_mic         # Turn off the other switch

    on_turn_off:
      - logger.log: "Turning off ASR Mic UDP stream"
      - lambda: |-
          if (id(udp_streamer).is_running()) {
            id(udp_streamer).request_stop();  // Stop the stream when ASR mic is turned off
          }
  - platform: template
    name: "UDP Stream Comm Mic"
    entity_category: "diagnostic"
    id: use_comm_mic
    icon: mdi:microphone
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    on_turn_on:
      - logger.log: "Switching to Comm Mic for UDP stream"
      - micro_wake_word.stop:
      - delay: 500ms
      - lambda: |-
          if (id(udp_streamer).is_running()) {
            id(udp_streamer).request_stop();  // Stop current stream
            delay(500);  // Wait for stream to stop
          }
          id(udp_streamer).set_microphone(id(comm_mic));  // Set Comm mic
          id(udp_streamer).request_start(true);  // Start stream with Comm mic
      - switch.turn_off: use_asr_mic           # Turn off the other switch

    on_turn_off:
      - logger.log: "Turning off Comm Mic UDP stream"
      - lambda: |-
          if (id(udp_streamer).is_running()) {
            id(udp_streamer).request_stop();  // Stop the stream when Comm mic is turned off
          }
      - delay: 500ms
      - micro_wake_word.start:

select:
  - platform: template
    name: TAS2780 AMP LEVEL (dbV)
    id: tas_amp_level_select
    options:
     - "11"
     - "11.5"
     - "12"
     - "12.5"
     - "13"
     - "13.5"
     - "14"
     - "14.5"
     - "15"
     - "15.5"
     - "16"
     - "16.5"
     - "17"
     - "17.5"
     - "18"
     - "18.5"
     - "19"
     - "19.5"
     - "20"
     - "20.5"
     - "21"
    initial_option: "15"
    optimistic: true
    on_value:
      - tas2780.update_config:
          amp_level_idx: !lambda |-
            auto index = id(tas_amp_level_select).active_index();
            if (index.has_value()){
              return index.value();
            }
            ESP_LOGI("main", "No amp level selected");

number:
  - platform: template
    name: Volume Range Min
    id: vol_rng_min
    mode: "slider"
    optimistic: true
    min_value: 0
    max_value: 1.
    step: .05
    initial_value: .3
    on_value:
      then:
        - tas2780.update_config:
            vol_range_min: !lambda "return x;"

  - platform: template
    name: Volume Range Max
    id: vol_rng_max
    mode: "slider"
    optimistic: true
    min_value: 0
    max_value: 1.
    initial_value: 1.
    step: .05
    on_value:
      then:
        - tas2780.update_config:
            vol_range_max: !lambda "return x;"