ld2410:

uart:
  tx_pin: GPIO43
  rx_pin: GPIO44
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

button:
  - platform: ld2410
    factory_reset:
      name: "LD2410 factory reset"
    restart:
      name: "LD2410 sensor restart"
    query_params:
      name: LD2410 update sensors

select:
  - platform: ld2410
    distance_resolution:
      name: distance resolution
    light_function:
        name: light function
        disabled_by_default: true

sensor:
  - platform: ld2410
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      disabled_by_default: true
      name: Moving Energy
    still_energy:
      disabled_by_default: true
      name: Still Energy
    detection_distance:
      disabled_by_default: true
      name: Detection Distance
    light:
      name: illuminance level
      disabled_by_default: true
    g0:
      move_energy:
        name: g0 moving energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 moving energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 moving energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 moving energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 moving energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 moving energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 moving energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 moving energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 moving energy
      still_energy:
        name: g8 still energy

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

number:
  - platform: ld2410
    timeout:
      name: timeout
    max_move_distance_gate:
      name: max moving distance gate
    max_still_distance_gate:
      name: max still distance gate
    light_threshold:
      name: light threshold
      disabled_by_default: true
    g0:
      move_threshold:
        name: g0 moving threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 moving threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 moving threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 moving threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 moving threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 moving threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 moving threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 moving threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 moving threshold
      still_threshold:
        name: g8 still threshold
  
switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: "control bluetooth"