globals:
  - id: improv_ble_in_progress
    type: bool
    restore_value: no
    initial_value: 'false'

wifi:
  id: wifi_id
  on_connect:
    - lambda: id(improv_ble_in_progress) = false;
    - script.execute: control_leds
  on_disconnect:
    - script.execute: control_leds

improv_serial:

